apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
  namespace: all-in-market
  labels:
    app: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      name: category-service
      labels:
        app: category-service
    spec:
      containers:
        - name: category-service
          image: albertsereda/all-in-market-category-service
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_IMPORT
              value: file:/config/
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: category-service-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: category-service-config
          configMap:
            name: category-service-config
      restartPolicy: Always